# permissions for end users to edit keyrequests.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: keyrequest-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: quantum-manager
    app.kubernetes.io/part-of: quantum-manager
    app.kubernetes.io/managed-by: kustomize
  name: keyrequest-editor-role
rules:
- apiGroups:
  - quantum-manager.io
  resources:
  - keyrequests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - quantum-manager.io
  resources:
  - keyrequests/status
  verbs:
  - get
