---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - keyrequest.quantum-manager.io
  resources:
  - keyrequests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - keyrequest.quantum-manager.io
  resources:
  - keyrequests/finalizers
  verbs:
  - update
- apiGroups:
  - keyrequest.quantum-manager.io
  resources:
  - keyrequests/status
  verbs:
  - get
  - patch
  - update
